### ISSUE TITLE
Don't duplicate inline styles

### ISSUE THREAD

**Issue by DSafari** [meanthemes/meanMenu#32]
Inline height of menu is duplicated currently.

Adding this solves the height issues but prevents animations:

``` css
.mean-container .mean-nav ul {
     height: auto !important;
}
```

Could inline styles be removed after cloning?
